debug: true

http:
  address: 0.0.0.0
  port: 3008

bap:
   id: "bap.dhiway.com"
   caller_uri: "https://beckn-adapter.dhiway.net/bap/caller"
   domain: "ONDC:TRV10"
   version: "2.0.0"
   ttl: "PT30S"